### ISSUE TITLE
v0.12.0 release doesn't work with current NeoVim

### ISSUE THREAD

**Issue by asankah** [google/vroom#106]
But the master branch works for me. The culprit seems to be the use of `NeoVim.with_hook` which was removed from NeoVim `python-client` in version 0.1.6.

**Comment by michaelmior** [comment]
Seeing the same issue. Here's the full error message I get:

```
ERROR: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/vroom/runner.py", line 74, in __call__
    self.env.vim.Start()
  File "/usr/lib/python3/dist-packages/vroom/neovim_mod.py", line 44, in Start
    self.nvim_unicode = self.nvim.with_hook(neovim.DecodeHook())
AttributeError: 'Nvim' object has no attribute 'with_hook'
```

**Comment by dbarnett** [comment]
I built a 0.13.0 release that should fix it: https://github.com/google/vroom/releases/tag/v0.13.0

**Comment by dbarnett** [comment]
I should mention that neovim support has preexisting issues and tends to hang for most of our vroom tests. See #83 and #100. So 0.13.0 may not get you all the way there if you were trying to get existing vroom tests to work.
