### ISSUE TITLE
Vroom needs a logo / icon

### ISSUE THREAD

**Issue by dbarnett** [google/vroom#82]
Would be cool if we had a logo to include in the docs and the deb.

I'm assuming this would be some kind of a "V" with speed axes or tires spinning or something else speed-related, but could be something more creative if anyone has ideas.

**Comment by groschovskiy** [comment]
I can draw cute logo for vroom if Google allow

**Comment by dbarnett** [comment]
Go for it. As long as it doesn't use Google branding and OSS license/copyright like the vroom code, no special permission should be required for it.

**Comment by groschovskiy** [comment]
Okay. Today I try make cute logo and push to repository

**Comment by groschovskiy** [comment]
We need just a nice logo or the inscription vroom also must be present?

**Comment by dbarnett** [comment]
Anything helps. I was thinking a square image for app icon and favicon, and maybe some corresponding large logo analogous to https://raw.githubusercontent.com/neovim/neovim.github.io/master/logos/neovim-logo.png.

**Comment by groschovskiy** [comment]
@dbarnett check please my pull request

**Comment by dbarnett** [comment]
FWIW, I had something a little simpler in mind like this sketch:
![sketch-1439668437945 2](https://cloud.githubusercontent.com/assets/65244/9290766/e48a7b9c-4353-11e5-96ce-b4d3b9c1ea33.jpg)
That lends itself to making a square app icon from just the slanted V.

But this project is not a dictatorship, so we can start with what graphics we have now and iterate on the design later.

**Comment by xanderman** [comment]
I like that the V looks similar to the ViM logo V. I had thought of drawing something up with a V very like the ViM logo and the o's being tires with motion lines and maybe skid marks/smoke/flames. But my artistic skill is pretty much nil, so at best I'd consider something I made to be a rough spec for someone else to implement. :-)

**Comment by groschovskiy** [comment]
I try rework your logo @dbarnett in Sketch

**Comment by dbarnett** [comment]
@groschovskiy Cool, thanks!
