### ISSUE TITLE
Provide a simple reference to vroom syntax

### ISSUE THREAD

**Issue by malcolmr** [google/vroom#85]
e.g. a cheatsheet or otherwise that explains what `$` does, how to wrap lines, and so on.

(from discussion in google/vim-codefmt#22)

**Comment by dbarnett** [comment]
I added a "cheat sheet" to the README. Also updated https://github.com/google/vroom/wiki/Tips-and-Tricks to add a few magic spells I've come up with for dealing with vroom's limitations.
